---
AWSTemplateFormatVersion: 2010-09-09
Description: Deploy Managed Kubernetes Resources - Worker Nodes
Parameters:
  # Paramenters are entirely optional.
  # but using them will make your cloudformation templates more reusable
  # use them for things that may change over time, such as instance type,
  # VPCs and so on.
    EnvironmentName:
        Description: The Name of the Env
        Type: String
        Default: capstone-green
Resources:
  CapKubeNodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

  CapKubeClusterNodegroupFleet:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !ImportValue cap-kube-cluster-name
      NodeRole: !GetAtt CapKubeNodeGroupRole.Arn
      NodegroupName: Capstone_node_group
      InstanceTypes:
        - t3.large
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 3
      Labels:
        cap-kube-node-group: True
        app: app
      Subnets:
          - !ImportValue 
              'Fn::Sub': '${EnvironmentName}-PriSub1Id'
          - !ImportValue 
              'Fn::Sub': '${EnvironmentName}-PriSub2Id'
      Tags: {"eks_role": "node_group"}