# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  lint:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/root/repo/blue-green/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-      
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd blue-green
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "/root/repo/blue-green/requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            cd blue-green
            make lint
  build:
    docker:
      - image: cimg/go:1.17
      
    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_cachine: true

      - run:
          name: Build Docker Image
          command: |
            cd blue-green
            docker build -t mada96/capstone_project:0.0_$CIRCLE_BRANCH .
            docker image ls

      - run:
          name: Push Docker Image
          command: |
            DOCKERPATH=mada96/capstone_project
            cd blue-green
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            docker image tag $DOCKERPATH:0.0 $DOCKERPATH:$CIRCLE_BRANCH
            docker push $DOCKERPATH:$CIRCLE_BRANCH
 
workflows:
  default:
    jobs:
      - lint:
          filters:
            branches:
              only: [blue, green]
      - build:
          requires: [lint]
          filters:
            branches:
              only: [blue, green]      
