# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  lint:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo/blue-green

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-      
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
  build:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo/blue-green

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: |
            sh build_docker.sh $CIRCLE_BRANCH

      - run:
          name: Push Docker Image
          command: |
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            sh push_docker.sh $CIRCLE_BRANCH
 
workflows:
  default:
    jobs:
      - lint:
          filters:
            branches:
              only: [blue, green]
      - build:
          requires: [lint]
          filters:
            branches:
              only: [blue, green]      
