apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue-deploy
  labels:
    app: app-deploy
    color: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      color: blue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
        color: blue
    spec:
      containers:
        - name: app
          image: mada96/capstone_project:green
          ports:
          - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80